// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoa4qm6kC-6n1nlZiI50Xc9cW8MZBoNWc',
    appId: '1:942045562037:web:91de977458d6de601d6afc',
    messagingSenderId: '942045562037',
    projectId: 'flutter-firebase-dersler-ac884',
    authDomain: 'flutter-firebase-dersler-ac884.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-ac884.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf_oRWNHzpHJlJCrL1fW61PVUKQaIuxfU',
    appId: '1:942045562037:android:1078e97ee3f0cb611d6afc',
    messagingSenderId: '942045562037',
    projectId: 'flutter-firebase-dersler-ac884',
    storageBucket: 'flutter-firebase-dersler-ac884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1cQQbaDL-6FqVBUdhTKTUoc6zyc4EOwo',
    appId: '1:942045562037:ios:e56358cb6ae9b41b1d6afc',
    messagingSenderId: '942045562037',
    projectId: 'flutter-firebase-dersler-ac884',
    storageBucket: 'flutter-firebase-dersler-ac884.appspot.com',
    iosClientId: '942045562037-tieoqic71cc41maeaeaosu9om47trn9o.apps.googleusercontent.com',
    iosBundleId: 'com.mepsanlearn.flutterFirebaseDersleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1cQQbaDL-6FqVBUdhTKTUoc6zyc4EOwo',
    appId: '1:942045562037:ios:e56358cb6ae9b41b1d6afc',
    messagingSenderId: '942045562037',
    projectId: 'flutter-firebase-dersler-ac884',
    storageBucket: 'flutter-firebase-dersler-ac884.appspot.com',
    iosClientId: '942045562037-tieoqic71cc41maeaeaosu9om47trn9o.apps.googleusercontent.com',
    iosBundleId: 'com.mepsanlearn.flutterFirebaseDersleri',
  );
}
