// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTcxUlveBH1uZ7Dv2wVDzTu9wtzREeqkg',
    appId: '1:280042516975:web:618fe9db8ab34aaba4061a',
    messagingSenderId: '280042516975',
    projectId: 'flutter-dersleri-2',
    authDomain: 'flutter-dersleri-2.firebaseapp.com',
    storageBucket: 'flutter-dersleri-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb2AxXar11Ee1rS1yrno2cqP-1KL56x_s',
    appId: '1:280042516975:android:6159be37904e4034a4061a',
    messagingSenderId: '280042516975',
    projectId: 'flutter-dersleri-2',
    storageBucket: 'flutter-dersleri-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACLeEzdnttAWhTZ6lZ7S2kYl8_kSJwKU',
    appId: '1:280042516975:ios:60a261d85ad10482a4061a',
    messagingSenderId: '280042516975',
    projectId: 'flutter-dersleri-2',
    storageBucket: 'flutter-dersleri-2.appspot.com',
    iosClientId: '280042516975-i3vu2s3nujdp8jhud7e3vau13kq4c8ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDeneme2',
  );
}
